# Generated by Django 6.0 on 2026-06-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('submission_uuid', models.UUIDField(blank=True, null=True)),
                ('facility_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('subcounty', models.CharField(blank=True, max_length=150, null=True)),
                ('mfl_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('client_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('client_age', models.IntegerField(blank=True, null=True)),
                ('visit_type', models.CharField(blank=True, max_length=50, null=True)),
                ('conditions_reported', models.TextField(blank=True, null=True)),
                ('date_patient_seen', models.DateField(blank=True, db_index=True, null=True)),
                ('kobo_submission_time', models.DateTimeField(blank=True, null=True)),
                ('kobo_last_modified', models.DateTimeField(blank=True, null=True)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField()),
            ],
            options={
                'db_table': 'kobo.raw_submissions',
                'ordering': ['-date_patient_seen'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('triggered_by', models.CharField(default='scheduler', max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_inserted', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('mapping_warnings', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kobo.sync_log',
                'ordering': ['-started_at'],
            },
        ),
    ]
