# Generated by Django 6.0 on 2026-06-30

from django.db import migrations

def create_schema_and_view(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            # Create schema if not exists
            cursor.execute("CREATE SCHEMA IF NOT EXISTS kobo;")
            
            # Create unnested view
            cursor.execute(r"""
                CREATE OR REPLACE VIEW kobo.v_moh763_unnested AS
                SELECT
                    id,
                    submission_id,
                    facility_name,
                    county,
                    subcounty,
                    mfl_code,
                    date_patient_seen,
                    
                    -- MOH 763 Age Buckets
                    CASE
                      WHEN client_age < 10 THEN '0-9'
                      WHEN client_age BETWEEN 10 AND 18 THEN '10-18'
                      WHEN client_age BETWEEN 19 AND 24 THEN '19-24'
                      WHEN client_age BETWEEN 25 AND 34 THEN '25-34'
                      WHEN client_age BETWEEN 35 AND 64 THEN '35-64'
                      WHEN client_age >= 65 THEN '65+'
                    END AS age_group,
                    
                    lower(substr(client_sex, 1, 1)) AS sex,
                    
                    -- Normalize Visit Type
                    CASE WHEN visit_type ILIKE 'new%' THEN 'New' ELSE 'Revisit' END AS visit_category,
                    
                    -- Unnest the space-separated conditions into individual rows
                    trim(unnest(regexp_split_to_array(conditions_reported, '\s+'))) AS condition_raw
                FROM "kobo.raw_submissions";
            """)

def drop_schema_and_view(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute("DROP VIEW IF EXISTS kobo.v_moh763_unnested;")

class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_schema_and_view, drop_schema_and_view),
    ]
