"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set DJANGO_SECRET_KEY as an environment variable.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-0kzz5qyd8-g=2&$%r#lvpzjl=$ftq^qz06etd3_!=6^+%p7jc4'  # dev fallback only
)

# SECURITY WARNING: don't run with debug turned on in production!
# In production, set DJANGO_DEBUG=False as an environment variable.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() not in ('false', '0', 'no')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local
    'projects',
    'pm',
    'budget',
    'researchers',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.UserPresenceMiddleware',
]

# In production, set CORS_ALLOWED_ORIGINS_LIST=https://yourdomain.com,https://www.yourdomain.com
_cors_env = os.environ.get('CORS_ALLOWED_ORIGINS_LIST', '')
CORS_ALLOWED_ORIGINS = (
    [u.strip() for u in _cors_env.split(',') if u.strip()]
    if _cors_env
    else [
        "http://localhost:5173",
        "http://localhost:5174",
    ]
)

CORS_ALLOW_CREDENTIALS = True

_csrf_env2 = os.environ.get('CSRF_TRUSTED_ORIGINS_LIST', '')
CSRF_TRUSTED_ORIGINS = (
    [u.strip() for u in _csrf_env2.split(',') if u.strip()]
    if _csrf_env2
    else [
        "http://localhost:5173",
        "http://localhost:5174",
    ]
)

# CSRF Settings for Frontend Compatibility
CSRF_COOKIE_HTTPONLY = False   # Allow JS to read the token (required for SPA CSRF pattern)
CSRF_USE_SESSIONS = False       # Ensure cookie-based CSRF is used
SESSION_COOKIE_HTTPONLY = True  # Prevent JS from reading the session cookie (XSS protection)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── Email Configuration ──────────────────────────────────────────────────────
# Dev: emails print to terminal (see the banner with the reset link)
# Prod: set the environment variables below and set EMAIL_USE_SMTP=true
#
# Required env vars for production SMTP:
#   EMAIL_USE_SMTP=true
#   EMAIL_HOST=smtp.yourprovider.com   (e.g. smtp.gmail.com)
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=your@email.com
#   EMAIL_HOST_PASSWORD=yourpassword
#   DEFAULT_FROM_EMAIL=CHQI Dashboard <no-reply@chqi.org>
#   FRONTEND_URL=https://yourdomain.com  (used in reset link)

_use_smtp = os.environ.get('EMAIL_USE_SMTP', 'false').lower() == 'true'

if _use_smtp:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'CHQI Dashboard <no-reply@chqi.org>')
else:
    # Development — prints to terminal with a clear banner
    EMAIL_BACKEND = 'config.email_backend.NoWrapConsoleEmailBackend'

# Frontend URL — used in password reset links.
# Dev:  http://localhost:5173  (React dev server)
# Prod: set FRONTEND_URL=https://yourdomain.com as an env var
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
# Logging Configuration

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log',
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'formatter': 'verbose',
        },
        'django_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['django_file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'pm': {
            'handlers': ['debug_file', 'console', 'error_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'projects': {
            'handlers': ['debug_file', 'console', 'error_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'frontend': {
            'handlers': ['debug_file', 'console', 'error_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)
