# Generated by Django 6.0 on 2026-01-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='projectfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('word', 'Word'), ('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.filefolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='projectfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.filefolder'),
        ),
    ]
