# Generated by Django 6.0 on 2026-07-15 07:49

import projects.models
from django.db import migrations, models


def backfill_working_days(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        if not project.working_days:
            project.working_days = [0, 1, 2, 3, 4]
            project.save(update_fields=['working_days'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='working_days',
            field=models.JSONField(blank=True, default=projects.models.default_working_days, help_text='Active weekday numbers: 0=Mon 1=Tue 2=Wed 3=Thu 4=Fri 5=Sat 6=Sun'),
        ),
        migrations.RunPython(backfill_working_days, migrations.RunPython.noop),
    ]
