# Generated by Django 6.0 on 2026-01-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectfile_options_projectfile_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
