# Generated by Django 6.0 on 2026-01-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('review', 'Review'), ('in_progress', 'In Progress'), ('upcoming', 'Upcoming'), ('overdue', 'Overdue')], default='upcoming', max_length=20),
        ),
    ]
