# Generated by Django 6.0 on 2026-03-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectfile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='holidays',
            field=models.JSONField(blank=True, default=list, help_text='Non-working dates as ISO-8601 strings'),
        ),
        migrations.AddField(
            model_name='project',
            name='hours_per_day',
            field=models.IntegerField(default=8, help_text='Working hours per day'),
        ),
        migrations.AddField(
            model_name='project',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text='Active weekday numbers: 0=Mon 1=Tue 2=Wed 3=Thu 4=Fri 5=Sat 6=Sun'),
        ),
    ]
