# Generated by Django 6.0 on 2026-07-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name shown above the embedded report', max_length=200)),
                ('division', models.CharField(blank=True, help_text="Grouping label, e.g. 'Division of Mental Health, Kenya'. Dashboards with the same division are grouped together.", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional blurb shown under the title')),
                ('embed_url', models.URLField(help_text="PowerBI 'Publish to web' embed URL (https://app.powerbi.com/view?r=...)", max_length=2000)),
                ('is_visible', models.BooleanField(default=True, help_text='Toggle to show/hide this dashboard on the public site')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within a division')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Dashboard',
                'verbose_name_plural': 'Public Dashboards',
                'ordering': ['division', 'display_order', 'title'],
            },
        ),
    ]
