# Generated by Django 6.0 on 2026-06-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DmhRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('rows_upserted', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('trigger', models.CharField(choices=[('cron', 'Cron'), ('manual', 'Manual')], default='cron', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DmhAnalyticsFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(db_index=True, max_length=40)),
                ('org_unit_id', models.CharField(max_length=20)),
                ('period_id', models.CharField(db_index=True, max_length=10)),
                ('data_element', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.CharField(blank=True, default='', max_length=2)),
                ('month', models.CharField(blank=True, default='', max_length=2)),
                ('period_type', models.CharField(blank=True, default='', max_length=20)),
                ('facility', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('county', models.CharField(blank=True, default='', max_length=100)),
                ('subcounty', models.CharField(blank=True, default='', max_length=150)),
                ('ward', models.CharField(blank=True, default='', max_length=150)),
                ('as_of_date', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['period_id'], name='dmh_dashboa_period__09883d_idx'), models.Index(fields=['county', 'period_id'], name='dmh_dashboa_county_ce88f7_idx')],
                'unique_together': {('org_unit_id', 'period_id', 'data_element', 'name', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='DmhReportingFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(db_index=True, max_length=40)),
                ('org_unit_id', models.CharField(max_length=20)),
                ('period_id', models.CharField(db_index=True, max_length=10)),
                ('data_element', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=50)),
                ('metric', models.CharField(max_length=50)),
                ('dataset', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.CharField(blank=True, default='', max_length=2)),
                ('month', models.CharField(blank=True, default='', max_length=2)),
                ('period_type', models.CharField(blank=True, default='', max_length=20)),
                ('facility', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('county', models.CharField(blank=True, default='', max_length=100)),
                ('subcounty', models.CharField(blank=True, default='', max_length=150)),
                ('ward', models.CharField(blank=True, default='', max_length=150)),
                ('as_of_date', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['period_id'], name='dmh_dashboa_period__bc3313_idx'), models.Index(fields=['county', 'period_id'], name='dmh_dashboa_county_057534_idx')],
                'unique_together': {('org_unit_id', 'period_id', 'data_element', 'name', 'metric', 'profile')},
            },
        ),
    ]
