# Generated by Django 6.0 on 2026-06-22 06:07
"""
Creates Postgres views that expose dmh_dashboard_dmhreportingfact in the
exact column names/types the Power BI M queries expect (PascalCase, Int64).

These views exist as a compatibility layer so existing .pbix M
transformations can swap their `Source =` step from a local CSV file to a
Postgres query without any downstream changes.

Why views and not direct table access:
  - M code expects PascalCase columns ("OrgUnit_ID") + Int64 types.
  - Underlying table stores snake_case + CharField (to preserve DHIS2
    dirty data at ingest time).
  - View does the rename + cast at the DB layer once.

The view is filtered by profile, so each Fact_ReportingCompliance_* table
points at its own view, mirroring the old one-CSV-per-form layout.
"""
from django.db import migrations


# Reusable SQL template — one view per reporting profile.
# Columns/types mirror what the M `#"Changed Type"` step enforces.
VIEW_TEMPLATE = """
CREATE OR REPLACE VIEW {view_name} AS
SELECT
    org_unit_id  AS "OrgUnit_ID",
    period_id::bigint     AS "Period_ID",
    value::numeric::bigint AS "Value",
    data_element          AS "DataElement",
    name                  AS "name",
    year::bigint          AS "Year",
    quarter               AS "Quarter",
    NULLIF(month, '')::bigint  AS "Month",
    period_type           AS "Period_Type",
    metric                AS "Metric",
    dataset               AS "DataSet",
    facility              AS "Facility",
    country               AS "Country",
    county                AS "County",
    subcounty             AS "SubCounty",
    ward                  AS "Ward"
FROM dmh_dashboard_dmhreportingfact
WHERE profile = '{profile}';
"""

REPORTING_VIEWS = [
    ("v_reporting_moh_717",      "moh_717"),
    ("v_reporting_moh_705_744a", "moh_705_744a"),
    ("v_reporting_moh_647",      "moh_647"),
    ("v_reporting_moh_515",      "moh_515"),
    ("v_reporting_moh_711",      "referrals"),  # extractor labels MOH 711 as "referrals"
]


class Migration(migrations.Migration):

    dependencies = [
        ('dmh_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="\n".join(
                VIEW_TEMPLATE.format(view_name=v, profile=p)
                for v, p in REPORTING_VIEWS
            ),
            reverse_sql="\n".join(
                f'DROP VIEW IF EXISTS {v} CASCADE;'
                for v, _ in REPORTING_VIEWS
            ),
        ),
    ]
