# Generated by Django 6.0 on 2026-06-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmh_dashboard', '0005_aux_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmhAllFacilitiesWithCuInfo',
            fields=[
                ('org_unit_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('facility', models.CharField(max_length=255)),
                ('ward', models.CharField(blank=True, default='', max_length=255)),
                ('subcounty', models.CharField(blank=True, default='', max_length=255)),
                ('county', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('cu_status', models.CharField(blank=True, default='', max_length=255)),
                ('cu_count', models.IntegerField(default=0)),
                ('community_units_list', models.TextField(blank=True, null=True)),
                ('has_cus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DmhAllKhisFacilities',
            fields=[
                ('org_unit_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('facility', models.CharField(max_length=255)),
                ('ward', models.CharField(blank=True, default='', max_length=255)),
                ('subcounty', models.CharField(blank=True, default='', max_length=255)),
                ('county', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('facility_type', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DmhCuFacilityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_unit_id', models.CharField(max_length=50)),
                ('community_unit_name', models.CharField(max_length=255)),
                ('facility_id', models.CharField(max_length=50)),
                ('facility_name', models.CharField(max_length=255)),
                ('ward', models.CharField(blank=True, default='', max_length=255)),
                ('subcounty', models.CharField(blank=True, default='', max_length=255)),
                ('county', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DmhEchisScreeningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=255)),
                ('last_1_month', models.IntegerField(default=0)),
                ('last_month', models.IntegerField(default=0)),
                ('last_3_months', models.IntegerField(default=0)),
                ('last_6_months', models.IntegerField(default=0)),
                ('year_to_date_ytd', models.IntegerField(default=0)),
                ('last_12_months', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DmhEchisScreeningReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('community_unit', models.CharField(max_length=255)),
                ('metric_id', models.CharField(max_length=255)),
                ('period_start', models.DateTimeField()),
                ('sum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DmhKamiliNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('county', models.CharField(max_length=255)),
                ('work_station', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DmhMergedEchisKhisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('community_unit', models.CharField(max_length=255)),
                ('metric_id', models.CharField(max_length=255)),
                ('period_start', models.DateTimeField()),
                ('sum', models.IntegerField(default=0)),
                ('community_unit_standardized', models.CharField(blank=True, default='', max_length=255)),
                ('community_unit_id', models.CharField(blank=True, default='', max_length=50)),
                ('community_unit_name', models.CharField(blank=True, default='', max_length=255)),
                ('facility_id', models.CharField(blank=True, default='', max_length=50)),
                ('facility_name', models.CharField(blank=True, default='', max_length=255)),
                ('ward', models.CharField(blank=True, default='', max_length=255)),
                ('subcounty', models.CharField(blank=True, default='', max_length=255)),
                ('county_standardized', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('is_matched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DmhNationalPsychHr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('mental_health_nurses', models.IntegerField(default=0)),
                ('mental_health_clinical_officers', models.IntegerField(default=0)),
                ('psychiatrist_consultant', models.IntegerField(default=0)),
            ],
        ),
    ]
