# Generated by Django 6.0 on 2026-07-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmh_dashboard', '0007_aux_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmhFacilityHierarchy',
            fields=[
                ('org_unit_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('org_unit_code', models.CharField(blank=True, default='', max_length=50)),
                ('facility', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('county', models.CharField(blank=True, default='', max_length=100)),
                ('county_code', models.CharField(blank=True, default='', max_length=50)),
                ('subcounty', models.CharField(blank=True, default='', max_length=150)),
                ('subcounty_code', models.CharField(blank=True, default='', max_length=50)),
                ('ward', models.CharField(blank=True, default='', max_length=150)),
                ('ward_code', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
