# Generated by Django 6.0 on 2026-03-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='e.g. Principal Investigator', max_length=200)),
                ('specialty', models.CharField(blank=True, help_text='e.g. Health Systems Research', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short biography displayed on the public site')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, help_text='Profile photo (recommended: square, at least 400x400px)', null=True, upload_to='researchers/')),
                ('is_visible', models.BooleanField(default=True, help_text='Toggle to show/hide this researcher on the public website')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Researcher',
                'verbose_name_plural': 'Researchers',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
