# Generated by Django 6.0 on 2026-04-27 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('comment', 'Commented'), ('assigned', 'Assigned'), ('status_change', 'Changed Status')], max_length=20)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('human', 'Human'), ('equipment', 'Equipment'), ('material', 'Material')], default='human', max_length=20)),
                ('cost_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('wbs_code', models.CharField(blank=True, default='', help_text="WBS code, e.g. '1.2.3'", max_length=50)),
                ('task_type', models.CharField(choices=[('work_package', 'Work Package'), ('milestone', 'Milestone'), ('summary_task', 'Summary Task')], default='work_package', max_length=20)),
                ('sort_order', models.IntegerField(default=0, help_text='Display ordering within same parent level')),
                ('start_date', models.DateField(blank=True, help_text='Auto-set by CPM engine from early_start', null=True)),
                ('duration', models.IntegerField(default=1, help_text='Duration in working days (0 for milestones, auto for summary tasks)')),
                ('constraint_type', models.CharField(choices=[('as_soon_as_possible', 'As Soon As Possible'), ('must_start_on', 'Must Start On'), ('start_no_earlier_than', 'Start No Earlier Than'), ('start_no_later_than', 'Start No Later Than'), ('must_finish_on', 'Must Finish On'), ('finish_no_earlier_than', 'Finish No Earlier Than'), ('finish_no_later_than', 'Finish No Later Than')], default='as_soon_as_possible', max_length=30)),
                ('constraint_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('early_start', models.DateField(blank=True, null=True)),
                ('early_finish', models.DateField(blank=True, null=True)),
                ('late_start', models.DateField(blank=True, null=True)),
                ('late_finish', models.DateField(blank=True, null=True)),
                ('total_float', models.IntegerField(blank=True, help_text='Total float in working days', null=True)),
                ('free_float', models.IntegerField(blank=True, help_text='Free float in working days', null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='pm.task')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pm.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pm.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], default='FS', max_length=2)),
                ('lag', models.IntegerField(default=0, help_text='Lag in working days (positive=delay, negative=lead)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.project')),
                ('predecessor_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_deps', to='pm.task')),
                ('successor_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_deps', to='pm.task')),
            ],
            options={
                'ordering': ['predecessor_task__sort_order'],
                'unique_together': {('predecessor_task', 'successor_task')},
            },
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percentage', models.IntegerField(default=100)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pm.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pm.task')),
            ],
            options={
                'unique_together': {('task', 'resource')},
            },
        ),
    ]
