# Generated by Django 6.0 on 2026-01-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_activitylog_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('comment', 'Commented'), ('assigned', 'Assigned'), ('status_change', 'Changed Status')], max_length=20),
        ),
    ]
