# Generated by Django 6.0 on 2026-01-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
