# Generated by Django 6.0 on 2026-03-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_activitylog_target_id'),
        ('projects', '0007_add_scheduling_calendar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='constraint_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='constraint_type',
            field=models.CharField(choices=[('as_soon_as_possible', 'As Soon As Possible'), ('must_start_on', 'Must Start On'), ('start_no_earlier_than', 'Start No Earlier Than'), ('start_no_later_than', 'Start No Later Than'), ('must_finish_on', 'Must Finish On'), ('finish_no_earlier_than', 'Finish No Earlier Than'), ('finish_no_later_than', 'Finish No Later Than')], default='as_soon_as_possible', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='early_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='early_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='free_float',
            field=models.IntegerField(blank=True, help_text='Free float in working days', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='late_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='late_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pm.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display ordering within same parent level'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('work_package', 'Work Package'), ('milestone', 'Milestone'), ('summary_task', 'Summary Task')], default='work_package', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='total_float',
            field=models.IntegerField(blank=True, help_text='Total float in working days', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='wbs_code',
            field=models.CharField(blank=True, default='', help_text="WBS code, e.g. '1.2.3'", max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration in working days (0 for milestones, auto for summary tasks)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Auto-set by CPM engine from early_start', null=True),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('human', 'Human'), ('equipment', 'Equipment'), ('material', 'Material')], default='human', max_length=20)),
                ('cost_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], default='FS', max_length=2)),
                ('lag', models.IntegerField(default=0, help_text='Lag in working days (positive=delay, negative=lead)')),
                ('predecessor_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_deps', to='pm.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.project')),
                ('successor_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_deps', to='pm.task')),
            ],
            options={
                'ordering': ['predecessor_task__sort_order'],
                'unique_together': {('predecessor_task', 'successor_task')},
            },
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percentage', models.IntegerField(default=100)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pm.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pm.task')),
            ],
            options={
                'unique_together': {('task', 'resource')},
            },
        ),
    ]
